---
nodes_ipv4: []
nodes_ipv6: []
datastore_host: 0.0.0.0
datastore_port: 2379
cluster_dns: 10.254.0.10
cluster_domain: k8s.cluster
k8s_master_service_cluster_ip: '10.254.0.0/16'
k8s_master_config: '/etc/kubernetes'
k8s_master_pod_infra_image: 'registry.access.redhat.com/rhel7/pod-infrastructure'
k8s_master_pod_infra_image_tag: 'latest'
k8s_master_api_server_image: 'registry.access.redhat.com/rhel7/kubernetes-apiserver'
k8s_master_api_server_image_tag: 'latest'
k8s_master_controller_mgr_image: 'registry.access.redhat.com/rhel7/kubernetes-controller-mgr'
k8s_master_controller_mgr_image_tag: 'latest'
k8s_master_scheduler_image: 'registry.access.redhat.com/rhel7/kubernetes-scheduler'
k8s_master_scheduler_image_tag: 'latest'
k8s_master_kubedns_image: 'gcr.io/google_containers/kubedns-amd64'
k8s_master_kubedns_image_tag: '1.7'
k8s_master_dnsmasq_image: 'gcr.io/google_containers/kube-dnsmasq-amd64'
k8s_master_dnsmasq_image_tag: '1.3'
k8s_master_healthz_image: 'gcr.io/google_containers/exechealthz-amd64'
k8s_master_healthz_image_tag: '1.1'
